node {
  ws('/var/jenkins_home/workspace/playground-projects'){
    stage('Build') {
        def workspace = pwd()
        echo 'Building....'
        echo "${workspace}"
    }
    stage('Test') {
        echo 'Building....'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
  }
}
