node {
    checkout([$class: 'GitSCM', branches: [[name: '*/feature/random-quotes/jenkins-build-trigger']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'random-quotes/.*']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Mksony/playground-projects']]])

    docker.image('node:8.1.0').inside('--user node') {
        withEnv([
        /* Override the npm cache directory to avoid: EACCES: permission denied, mkdir '/.npm' */
        'npm_config_cache=npm-cache',
        /* set home to our current directory because other bower
        * nonsense breaks with HOME=/, e.g.:
        * EACCES: permission denied, mkdir '/.config'
        */
        'HOME=.',
        'CI=true'
        ]) {
            stage('Install dependencies') {
                sh 'cd random-quotes && npm install'
            }

            stage('Run tests') {
                sh 'cd random-quotes && npm run test'
            }

        }
    }
}
