node {
    customWorkspace '/var/jenkins_home/playground-projects'
    stage('Build') {
        def workspace = pwd()
        echo 'Building....'
        echo "${workspace}"
    }
    stage('Test') {
        echo 'Building....'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}