node {
    checkout([$class: 'GitSCM', branches: [[name: "${BRANCH_NAME}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'express-boilerplate/.*'], [$class: 'PruneStaleBranch'], [$class: 'CloneOption', depth: 0, noTags: false, reference: "${JENKINS_HOME}/repos/playground-projects", shallow: false]], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Mksony/playground-projects.git']]])

    docker.image('node:8.9.1').inside('--user node') {
        withEnv([
        'CI=true'
        ]) {

            stage('Install dependencies') {
                sh 'cd express-boilerplate && yarn'
            }

            stage('Run tests') {
                sh 'cd express-boilerplate && yarn test:ci'
                stash includes: 'express-boilerplate/junit.xml', name: 'testResults'
            }

        }
    }
    stage('Publish test results') {
        unstash 'testResults'
        junit 'express-boilerplate/junit.xml'
    }
}
