"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var _1 = require("./");
// tslint:disable
var addDefaultStyles = function () { return styled_components_1.injectGlobal(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  html, body {\n    max-width: 100%;\n    overflow-x: hidden;\n  }\n  body {\n    /* system font https://medium.com/designing-medium/system-shock-6b1dc6d6596f */\n    font-family: \"Source Sans Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif;\n    color: ", ";\n    overflow-y: scroll; /* has to be scroll, not auto */\n    -webkit-overflow-scrolling: touch;\n    min-height: 100vh;\n  }\n\n  li, p, a {\n    font-size: 1rem;\n    line-height: 1.4;\n    ", "\n    ", "\n  }\n  h1, .h1 {\n    font-size: 2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    font-weight: bold;\n    ", "\n    ", "\n  }\n  h2, .h2 {\n    font-size: 1.8em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ", "\n    ", "\n  }\n  h3, .h3 {\n    font-size: 1.6em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ", "\n    ", "\n  }\n  h4, .h4 {\n    font-size: 1.4em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ", "\n    ", "\n  }\n  h5, .h5 {\n    font-size: 1.2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ", "\n    ", "\n  }\n  h6, .h6 {\n    font-size: 1.2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ", "\n    ", "\n  }\n  img {\n    max-width: 100%;\n  }\n"], ["\n  html, body {\n    max-width: 100%;\n    overflow-x: hidden;\n  }\n  body {\n    /* system font https://medium.com/designing-medium/system-shock-6b1dc6d6596f */\n    font-family: \"Source Sans Pro\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif;\n    color: ", ";\n    overflow-y: scroll; /* has to be scroll, not auto */\n    -webkit-overflow-scrolling: touch;\n    min-height: 100vh;\n  }\n\n  li, p, a {\n    font-size: 1rem;\n    line-height: 1.4;\n    ",
    "\n    ",
    "\n  }\n  h1, .h1 {\n    font-size: 2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    font-weight: bold;\n    ",
    "\n    ",
    "\n  }\n  h2, .h2 {\n    font-size: 1.8em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ",
    "\n    ",
    "\n  }\n  h3, .h3 {\n    font-size: 1.6em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ",
    "\n    ",
    "\n  }\n  h4, .h4 {\n    font-size: 1.4em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ",
    "\n    ",
    "\n  }\n  h5, .h5 {\n    font-size: 1.2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ",
    "\n    ",
    "\n  }\n  h6, .h6 {\n    font-size: 1.2em;\n    margin-bottom: .25em;\n    line-height: 1.2;\n    ",
    "\n    ",
    "\n  }\n  img {\n    max-width: 100%;\n  }\n"])), _1.colors.grey.dark, _1.media.sm(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n        font-size: 1.1rem;\n        line-height: 1.5;\n      "], ["\n        font-size: 1.1rem;\n        line-height: 1.5;\n      "]))), _1.media.md(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n        font-size: 1.2rem;\n        line-height: 1.5;\n      "], ["\n        font-size: 1.2rem;\n        line-height: 1.5;\n      "]))), _1.media.sm(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n        font-size: 2.4em;\n      "], ["\n        font-size: 2.4em;\n      "]))), _1.media.md(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n        font-size: 2.8em;\n      "], ["\n        font-size: 2.8em;\n      "]))), _1.media.sm(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n        font-size: 2em;\n      "], ["\n        font-size: 2em;\n      "]))), _1.media.md(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n        font-size: 2.2em;\n      "], ["\n        font-size: 2.2em;\n      "]))), _1.media.sm(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n        font-size: 1.8em;\n      "], ["\n        font-size: 1.8em;\n      "]))), _1.media.md(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n        font-size: 2em;\n      "], ["\n        font-size: 2em;\n      "]))), _1.media.sm(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n        font-size: 1.6em;\n      "], ["\n        font-size: 1.6em;\n      "]))), _1.media.md(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n        font-size: 1.8em;\n      "], ["\n        font-size: 1.8em;\n      "]))), _1.media.sm(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n        font-size: 1.4em;\n      "], ["\n        font-size: 1.4em;\n      "]))), _1.media.md(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n        font-size: 1.6em;\n      "], ["\n        font-size: 1.6em;\n      "]))), _1.media.sm(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n        font-size: 1.4em;\n      "], ["\n        font-size: 1.4em;\n      "]))), _1.media.md(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n        font-size: 1.6em;\n      "], ["\n        font-size: 1.6em;\n      "])))); };
exports.default = addDefaultStyles;
var templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_1;
